FROM rust:1.97.1-alpine3.23 AS builder

RUN apk update && \
    apk add --no-cache bash curl libc-dev binaryen libc6-compat musl-dev

WORKDIR /work

RUN rustup target add wasm32-unknown-unknown

RUN cargo install --locked trunk
RUN cargo install --locked wasm-bindgen-cli

COPY dev-tools ./

RUN trunk build --release
RUN cargo build --release --bin server

RUN mkdir build

FROM scratch AS runner

WORKDIR /work

COPY --from=builder /work/dist /work/dist
COPY --from=builder /work/target/release/server /work/server

