#FROM debian:bookworm-slim AS runner
#FROM alpine:3.22.4 AS runner
FROM scratch AS runner

WORKDIR /

COPY --chmod=755 target/work/server /app/
COPY --chmod=644 target/work/site /app/site

EXPOSE 80

ENV LEPTOS_SITE_ROOT=/app/site \
    LEPTOS_SITE_ADDR=0.0.0.0:80

CMD ["/app/server"]
