FROM rust:1.97.1-alpine3.23 AS builder

RUN apk update && \
    apk add --no-cache bash curl libc-dev binaryen

RUN curl --proto '=https' --tlsv1.2 -LsSf https://github.com/leptos-rs/cargo-leptos/releases/download/v0.3.6/cargo-leptos-installer.sh | sh

RUN rustup target add wasm32-unknown-unknown

WORKDIR /work

COPY dev-tools ./

ENV LEPTOS_TAILWIND_VERSION="v4.3.3"

RUN cargo leptos build --release -vv

FROM scratch AS runner

WORKDIR /work

COPY --from=builder /work/site /work/site
COPY --from=builder /work/target/release/server /work/server

